cmake: detect fts also in external lib
Not all libc implementations support fts. fts support may be added via
an external library.

One such example is musl libc. It doesn't support fts. But support for
fts can be added to the target device via musl-fts, which provides
libfts.

When libzip encounters such a setup (fts.h available but symbols in
libfts.so) the build fails at the linking stage:

zipcmp.c:(.text.startup+0x130): undefined reference to `fts_open'
/home/sk/tmp/openwrt/staging_dir/toolchain-mips_24kc_gcc-8.3.0_musl/lib/gcc/mips-openwrt-linux-musl/8.3.0/../../../../mips-openwrt-linux-musl/bin/ld: zipcmp.c:(.text.startup+0x172): undefined reference to `fts_read'

This commit sets up cmake so that it checks for fts symbols first in
libc and - if none encountered there - in an external libfts. So in case
libc provides fts nothing changes, libzip will use libc's fts symbols
(if fts.h is present). If on the other hand libc doesn't provide fts but
libfts does, it'll link it in where required (zipcmp).

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>